# Generated by Django 4.0.4 on 2022-04-19 15:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('etage', models.IntegerField()),
                ('nbre_lit', models.IntegerField()),
                ('nbre_chambre', models.IntegerField()),
                ('nbre_douche', models.IntegerField()),
                ('nbre_places_reservees', models.IntegerField()),
                ('espace_m2', models.FloatField()),
                ('meuble', models.BooleanField(blank=True, default=False)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=500)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reservation/photos')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('etage', models.IntegerField()),
                ('nbre_lit', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('nbre_places_reservees', models.IntegerField()),
                ('espace_m2', models.FloatField()),
                ('meuble', models.BooleanField(blank=True, default=False)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reservation/photos')),
                ('appartement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.appartement')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Propriete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tel', models.BigIntegerField(unique=True)),
                ('fax', models.BigIntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('nbre_etage', models.IntegerField()),
                ('descripion', models.CharField(max_length=500)),
                ('adresse', models.CharField(max_length=500)),
                ('matricule_fiscale', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeProprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypePropriete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tel', models.BigIntegerField(unique=True)),
                ('fax', models.BigIntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=500)),
                ('site_web', models.URLField(blank=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.typepropriete')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('propriete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.propriete')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationService',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('period', models.DurationField(default=datetime.timedelta(0))),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.chambre')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationDortoireDemande',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=500)),
                ('prenom', models.CharField(blank=True, max_length=500)),
                ('gender', models.CharField(choices=[('Male', 'Masculin'), ('Female', 'Feminin')], max_length=140, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=500)),
                ('specialite', models.CharField(blank=True, max_length=500)),
                ('message', models.TextField(blank=True)),
                ('dete_debut', models.DateField(blank=True, null=True)),
                ('period', models.CharField(blank=True, max_length=500)),
                ('nbre_lit', models.IntegerField()),
                ('status', models.CharField(choices=[('Waiting', 'En attente'), ('Closed', 'Clôturée'), ('Accepted', 'Acceptée')], max_length=140, null=True)),
                ('appartement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.appartement')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('universite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='universite_reservation', to='reservation.universite')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationDortoireConfirmee',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('demande_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.reservationdortoiredemande')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='propriete',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.typepropriete'),
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=500)),
                ('prenom', models.CharField(max_length=500)),
                ('raison_social', models.CharField(max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tel_num', models.BigIntegerField(unique=True)),
                ('propriete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.propriete')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.typeproprietaire')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code_lit', models.CharField(max_length=250)),
                ('est_reserve', models.BooleanField(default=False)),
                ('chambre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.chambre')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='appartement',
            name='propriete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.propriete'),
        ),
    ]
