from django.urls import include, path

from reservation.views import (
    AppartementRetrieveUpdateView,
    AppartementListCreateAPIView,
    ServiceRetrieveUpdateView,
    ServiceListCreateAPIView,
    UniversiteRetrieveUpdateView,
    UniversiteListCreateAPIView,
    ProprieteListCreateAPIView,
    ProprieteRetrieveUpdateView,
    DemandeReservationDortoireListCreateAPIView,
    DemandeReservationDortoireRetrieveUpdateView,
)

urlpatterns = [
    path(
        "appartements/",
        AppartementListCreateAPIView.as_view(),
        name="appartements",
    ),
    path(
        "appartements/<int:pk>/",
        AppartementRetrieveUpdateView.as_view(),
        name="appartement_info",
    ),
    path(
        "services/",
        ServiceListCreateAPIView.as_view(),
        name="services",
    ),
    path(
        "services/<int:pk>/",
        ServiceRetrieveUpdateView.as_view(),
        name="service_info",
    ),
    path(
        "universites/",
        UniversiteListCreateAPIView.as_view(),
        name="universites",
    ),
    path(
        "universites/<int:pk>/",
        UniversiteRetrieveUpdateView.as_view(),
        name="universite_info",
    ),
    path(
        "propriete/",
        ProprieteListCreateAPIView.as_view(),
        name="propriete",
    ),
    path(
        "propriete/<int:pk>/",
        ProprieteRetrieveUpdateView.as_view(),
        name="propriete_info",
    ),
    path(
        "demandedortoire/",
        DemandeReservationDortoireListCreateAPIView.as_view(),
        name="demande_dortoire",
    ),
    path(
        "demandedortoire/<int:pk>/",
        DemandeReservationDortoireRetrieveUpdateView.as_view(),
        name="demande_dortoire_info",
    ),
]
